trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout)
    path('accounts/', include('django.contrib.auth.urls')),
    path('customers/', include('customers.urls')),
    path('employees/', include('employees.urls')),
    path('', views.group_redirect, name='home')
]

trash_collector/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return self.username

trash_collector/customers/models.py
from django.db import models
# Create your models here.

# TODO: Finish customer model by adding necessary properties to fulfill user stories


class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', default=0, on_delete=models.CASCADE)

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

trash_collector/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm


class CustomUserForm(UserCreationForm):
    is_employee = forms.BooleanField(label="Check to register as employee", required=False)

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "is_employee")

    def save(self, commit=True):
        user = super(CustomUserForm, self).save(commit=False)
        user.is_employee = self.cleaned_data["is_employee"]

        if commit:
            user.save()
            if user.is_employee:
                employees = Group.objects.get(name="Employees")
                employees.user_set.add(user)
            else:
                customers = Group.objects.get(name="Customers")
                customers.user_set.add(user)
        return user

trash_collector/accounts/views.py
from django.contrib.auth import login
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy, reverse
from django.views import generic
from .forms import CustomUserForm


class RegisterView(generic.CreateView):
    form_class = CustomUserForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

trash_collector/customers/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Customer
# Create your views here.

# TODO: Create a function for each path created in customers/urls.py. Each will need a template as well.


def index(request):
    # get the logged in user within any view function
    user = request.user
    # This will be useful while creating a customer to assign the logged in user as the user foreign key
    # Will also be useful in any function that needs
    print(user)
    return render(request, 'customers/index.html')

trash_collector/employees/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.apps import apps

# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.


def index(request):
    # Get the Customer model from the other app
    Customer = apps.get_model('customers.Customer')
    return render(request, 'employees/index.html')

trash_collector/trash_collector/views.py
from django.shortcuts import redirect, render


def group_redirect(request):
    if request.user.groups.filter(name="Customers").exists():
        return redirect('/customers/')
    elif request.user.groups.filter(name="Employees").exists():
        return redirect('/employees/')
    else:
        return render(request, 'home.html')

trash_collector/customers/templates/customers/index.html
{% extends 'base.html' %}

{% block title %}Customer Home{% endblock %}

{% block header %} Customer Home {% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello customer {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %} Employee Home {% endblock %}

{% block header %} Employee Home {% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello Employee {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

trash_collector/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
    <p>Customer Navbar</p>
    {% elif group.name == "Employees" %}
    <p>Employee Navbar</p>
    {% endif %}
  {% endfor %}
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Portal{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attemp to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}